### ISSUE TITLE
How to change it to Extended Kalman Filter or Unscented Kalman Filter?

### ISSUE THREAD

**Issue by WestbrookZero** [JCLArriaga5/cimat_sort_rgbd#2]

**Comment by JCLArriaga5** [comment]
Hello, we are using the function inside opencv, I leave the [link](https://docs.opencv.org/master/dd/d6a/classcv_1_1KalmanFilter.html#details) of the documentation. They mention that you can modify transitionMatrix, controlMatrix, and measurementMatrix to get extended Kalman filter.

You could also check out some repositories on EKF and UKF or implement their equations and modify KalmanBoxTracker [impl](https://github.com/JCLArriaga5/cimat_sort_rgbd/tree/master/src/sort/impl) and [include](https://github.com/JCLArriaga5/cimat_sort_rgbd/tree/master/src/sort/include).

Here is the [SORT](https://arxiv.org/pdf/1602.00763.pdf) paper for 2D images.

**Comment by WestbrookZero** [comment]
Thank you for your reply !  I have two last questions .

The first question,  When I tested this project, tracking ID is increasing very fast , A few people at most per frame . After a while it was in the hundreds. how to solve it ? even though i use "x_get.p_id = trk_res->id;"  instead of "x_get.p_id = trk_res->id + 1;" . 
 
The second question,  Does this project's PCL based target detection support the DeepSort target tracking algorithm?

**Comment by JCLArriaga5** [comment]
Thanks for your comments!

Regarding the first question, I am going to review since I am not sure if it is because the fundamental truths are not being taken, the ones that are taken are those generated by the PCL detector for each frame or it is due to something else.

Regarding the second question, I think that the PCL detection can be used if you generate a state vector like the one used by deepsort, in [PersonCluster](https://pointclouds.org/documentation/classpcl_1_1people_1_1_person_cluster.html) you can check the information of the functions that can be used to obtain the detections: height, center , etc.

**Comment by WestbrookZero** [comment]
Is Unscented Kalman Filter or DeepSort tracking more effective than basic Kalman filter for this point cloud human detection project ?

**Comment by JCLArriaga5** [comment]
I'm sorry I can't tell you with certainty which one is better, you would have to do tests with each one of them before.
